### ISSUE TITLE
crash on recent ncurses

### ISSUE THREAD

**Issue by sss123next** [whdd/whdd#17]
```
              Program received signal SIGSEGV, Segmentation fault.
                                                                  0x00007ffff7f15499 in waddch () from /usr/x86_64-pc-linux-gnu/lib/libncurses.so.6
(gdb) where
#0  0x00007ffff7f15499 in waddch () from /usr/x86_64-pc-linux-gnu/lib/libncurses.so.6
#1  0x00007ffff7eebea6 in dlg_draw_box2 () from /usr/x86_64-pc-linux-gnu/lib/libdialog.so.15
#2  0x00007ffff7ee45b7 in dlg_menu () from /usr/x86_64-pc-linux-gnu/lib/libdialog.so.15
#3  0x00007ffff7ee5781 in dialog_menu () from /usr/x86_64-pc-linux-gnu/lib/libdialog.so.15
#4  0x0000555555558fbd in menu_choose_device ()
#5  0x0000555555558939 in main ()
```

sys-libs/ncurses-6.2
sys-apps/dialog-1.3_p20191210

**Comment by andrey-utkin** [comment]
Sorry for that and for the delay.
Old report, no clues, closing.
